/* 
Write a program to implement random early detection (RED)
congestion control algorithm. 
*/
import java.util.*;

public class RED {
  public static void main(String[] args) {
    Scanner in = new Scanner(System.in);
    System.out.println("Enter the maximum packets:");
    int maxPackets = in.nextInt();
    System.out.println("Enter the queue size:");
    int queueSize = in.nextInt();
    System.out.println("Enter the maximum probability:");
    double maxProbability = in.nextDouble();
    System.out.println("Enter the minimum probability:");
    double minProbability = in.nextDouble();

    Random random = new Random(System.currentTimeMillis());
    int queueLength = 0;
    double dropProbability = minProbability;
    for(int i = 0; i < maxPackets; i++)
    {
      if(queueLength == queueSize)
      {
        System.out.println("PACKETS DROPPED [QUEUE FULL]");
        dropProbability = minProbability;
      }
      else if(random.nextDouble() < minProbability)
      {
        System.out.println("PACKET DROPPED [RANDOM]");
        dropProbability = dropProbability + ((maxProbability-minProbability) / (maxPackets-1));
      }
      else 
      {
        System.out.println("PACKET ACCEPTED");
        queueLength = queueLength + 1;
        dropProbability = minProbability;
      }
    }
  }
}

// OUTPUT 1:
/*
Enter the maximum packets:
100
Enter the queue size:
20
Enter the maximum probability:
0.8
Enter the minimum probability:
0.2
PACKET ACCEPTED
PACKET ACCEPTED
PACKET DROPPED [RANDOM]
PACKET DROPPED [RANDOM]
PACKET ACCEPTED
PACKET ACCEPTED
PACKET ACCEPTED
PACKET ACCEPTED
PACKET ACCEPTED
PACKET ACCEPTED
PACKET DROPPED [RANDOM]
PACKET DROPPED [RANDOM]
PACKET ACCEPTED
PACKET ACCEPTED
PACKET ACCEPTED
PACKET ACCEPTED
PACKET ACCEPTED
PACKET ACCEPTED
PACKET ACCEPTED
PACKET ACCEPTED
PACKET ACCEPTED
PACKET ACCEPTED
PACKET ACCEPTED
PACKET ACCEPTED
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
*/

// OUTPUT 2:
/* 
Enter the maximum packets:
50
Enter the queue size:
10
Enter the maximum probability:
0.6
Enter the minimum probability:
0.4
PACKET ACCEPTED
PACKET ACCEPTED
PACKET ACCEPTED
PACKET DROPPED [RANDOM]
PACKET ACCEPTED
PACKET DROPPED [RANDOM]
PACKET ACCEPTED
PACKET ACCEPTED
PACKET DROPPED [RANDOM]
PACKET ACCEPTED
PACKET ACCEPTED
PACKET DROPPED [RANDOM]
PACKET DROPPED [RANDOM]
PACKET ACCEPTED
PACKET DROPPED [RANDOM]
PACKET DROPPED [RANDOM]
PACKET DROPPED [RANDOM]
PACKET ACCEPTED
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
PACKETS DROPPED [QUEUE FULL]
*/
